/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FLPCrowdSaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ETH_rate"
      | "USDT_rate"
      | "buyTokenByETH"
      | "buyTokenByUSDT"
      | "getTokenAmountETH"
      | "getTokenAmountUSDT"
      | "owner"
      | "renounceOwnership"
      | "setETHRate"
      | "setUSDTRate"
      | "setUSDTToken"
      | "token"
      | "transferOwnership"
      | "usdtToken"
      | "wallet"
      | "withdraw"
      | "withdrawErc20"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BuyTokenByETH"
      | "BuyTokenByUSDT"
      | "ETHRateChanged"
      | "OwnershipTransferred"
      | "SetUSDTToken"
      | "USDTRateChanged"
  ): EventFragment;

  encodeFunctionData(functionFragment: "ETH_rate", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDT_rate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyTokenByETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyTokenByUSDT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAmountETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAmountUSDT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setETHRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUSDTRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUSDTToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "wallet", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawErc20",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ETH_rate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDT_rate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyTokenByETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyTokenByUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAmountETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAmountUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setETHRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUSDTRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUSDTToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wallet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawErc20",
    data: BytesLike
  ): Result;
}

export namespace BuyTokenByETHEvent {
  export type InputTuple = [buyer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [buyer: string, amount: bigint];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuyTokenByUSDTEvent {
  export type InputTuple = [buyer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [buyer: string, amount: bigint];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ETHRateChangedEvent {
  export type InputTuple = [newRate: BigNumberish];
  export type OutputTuple = [newRate: bigint];
  export interface OutputObject {
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetUSDTTokenEvent {
  export type InputTuple = [tokenAddress: AddressLike];
  export type OutputTuple = [tokenAddress: string];
  export interface OutputObject {
    tokenAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace USDTRateChangedEvent {
  export type InputTuple = [newRate: BigNumberish];
  export type OutputTuple = [newRate: bigint];
  export interface OutputObject {
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FLPCrowdSale extends BaseContract {
  connect(runner?: ContractRunner | null): FLPCrowdSale;
  waitForDeployment(): Promise<this>;

  interface: FLPCrowdSaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ETH_rate: TypedContractMethod<[], [bigint], "view">;

  USDT_rate: TypedContractMethod<[], [bigint], "view">;

  buyTokenByETH: TypedContractMethod<[], [void], "payable">;

  buyTokenByUSDT: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTokenAmountETH: TypedContractMethod<
    [ethAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getTokenAmountUSDT: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setETHRate: TypedContractMethod<
    [newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setUSDTRate: TypedContractMethod<
    [newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setUSDTToken: TypedContractMethod<
    [token_address: AddressLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdtToken: TypedContractMethod<[], [string], "view">;

  wallet: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  withdrawErc20: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ETH_rate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDT_rate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyTokenByETH"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "buyTokenByUSDT"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTokenAmountETH"
  ): TypedContractMethod<[ethAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokenAmountUSDT"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setETHRate"
  ): TypedContractMethod<[newRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUSDTRate"
  ): TypedContractMethod<[newRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUSDTToken"
  ): TypedContractMethod<[token_address: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawErc20"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BuyTokenByETH"
  ): TypedContractEvent<
    BuyTokenByETHEvent.InputTuple,
    BuyTokenByETHEvent.OutputTuple,
    BuyTokenByETHEvent.OutputObject
  >;
  getEvent(
    key: "BuyTokenByUSDT"
  ): TypedContractEvent<
    BuyTokenByUSDTEvent.InputTuple,
    BuyTokenByUSDTEvent.OutputTuple,
    BuyTokenByUSDTEvent.OutputObject
  >;
  getEvent(
    key: "ETHRateChanged"
  ): TypedContractEvent<
    ETHRateChangedEvent.InputTuple,
    ETHRateChangedEvent.OutputTuple,
    ETHRateChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SetUSDTToken"
  ): TypedContractEvent<
    SetUSDTTokenEvent.InputTuple,
    SetUSDTTokenEvent.OutputTuple,
    SetUSDTTokenEvent.OutputObject
  >;
  getEvent(
    key: "USDTRateChanged"
  ): TypedContractEvent<
    USDTRateChangedEvent.InputTuple,
    USDTRateChangedEvent.OutputTuple,
    USDTRateChangedEvent.OutputObject
  >;

  filters: {
    "BuyTokenByETH(address,uint256)": TypedContractEvent<
      BuyTokenByETHEvent.InputTuple,
      BuyTokenByETHEvent.OutputTuple,
      BuyTokenByETHEvent.OutputObject
    >;
    BuyTokenByETH: TypedContractEvent<
      BuyTokenByETHEvent.InputTuple,
      BuyTokenByETHEvent.OutputTuple,
      BuyTokenByETHEvent.OutputObject
    >;

    "BuyTokenByUSDT(address,uint256)": TypedContractEvent<
      BuyTokenByUSDTEvent.InputTuple,
      BuyTokenByUSDTEvent.OutputTuple,
      BuyTokenByUSDTEvent.OutputObject
    >;
    BuyTokenByUSDT: TypedContractEvent<
      BuyTokenByUSDTEvent.InputTuple,
      BuyTokenByUSDTEvent.OutputTuple,
      BuyTokenByUSDTEvent.OutputObject
    >;

    "ETHRateChanged(uint256)": TypedContractEvent<
      ETHRateChangedEvent.InputTuple,
      ETHRateChangedEvent.OutputTuple,
      ETHRateChangedEvent.OutputObject
    >;
    ETHRateChanged: TypedContractEvent<
      ETHRateChangedEvent.InputTuple,
      ETHRateChangedEvent.OutputTuple,
      ETHRateChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SetUSDTToken(address)": TypedContractEvent<
      SetUSDTTokenEvent.InputTuple,
      SetUSDTTokenEvent.OutputTuple,
      SetUSDTTokenEvent.OutputObject
    >;
    SetUSDTToken: TypedContractEvent<
      SetUSDTTokenEvent.InputTuple,
      SetUSDTTokenEvent.OutputTuple,
      SetUSDTTokenEvent.OutputObject
    >;

    "USDTRateChanged(uint256)": TypedContractEvent<
      USDTRateChangedEvent.InputTuple,
      USDTRateChangedEvent.OutputTuple,
      USDTRateChangedEvent.OutputObject
    >;
    USDTRateChanged: TypedContractEvent<
      USDTRateChangedEvent.InputTuple,
      USDTRateChangedEvent.OutputTuple,
      USDTRateChangedEvent.OutputObject
    >;
  };
}
