import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import theme from "@/src/themes";
import { ColorModeScript } from "@chakra-ui/react";
import { Providers } from "@/src/components/Providers";
import { config } from "@/src/themes/config";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ColorModeScript initialColorMode={config.initialColorMode} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
